# Generated by Django 4.2.7 on 2025-09-19 16:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Ingredient name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Ingredient description', max_length=500)),
                ('category', models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('spice', 'Spice'), ('herb', 'Herb'), ('oil', 'Oil'), ('other', 'Other')], default='other', help_text='Ingredient category', max_length=50)),
                ('calories_per_100g', models.PositiveIntegerField(blank=True, help_text='Calories per 100 grams', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of recipes using this ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'recipes_ingredient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Recipe title/name', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Recipe description and overview', max_length=1000)),
                ('prep_time', models.PositiveIntegerField(help_text='Preparation time in minutes')),
                ('cook_time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('total_time', models.PositiveIntegerField(blank=True, help_text='Total time (prep + cook) in minutes', null=True)),
                ('servings', models.PositiveIntegerField(help_text='Number of servings this recipe makes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('featured_image', models.ImageField(blank=True, help_text='Main recipe image', null=True, upload_to='recipes/images/')),
                ('video_url', models.URLField(blank=True, help_text='Optional recipe video URL', null=True)),
                ('calories_per_serving', models.PositiveIntegerField(blank=True, help_text='Calories per serving', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether recipe is published and visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether recipe should be featured')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('popularity_score', models.FloatField(default=0.0, help_text='Calculated popularity score for recommendations')),
                ('author', models.ForeignKey(help_text='Recipe creator', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Primary recipe category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='categories.category')),
                ('difficulty_level', models.ForeignKey(help_text='Recipe difficulty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='categories.difficultylevel')),
                ('tags', models.ManyToManyField(blank=True, help_text='Recipe tags', related_name='recipes', to='categories.tag')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'recipes_recipe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='recipes.recipe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe View',
                'verbose_name_plural': 'Recipe Views',
                'db_table': 'recipes_view',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['recipe', '-viewed_at'], name='recipes_vie_recipe__a8699a_idx'), models.Index(fields=['user', '-viewed_at'], name='recipes_vie_user_id_37da5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional written review', max_length=1000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe Rating',
                'verbose_name_plural': 'Recipe Ratings',
                'db_table': 'recipes_rating',
                'ordering': ['-created_at'],
                'unique_together': {('recipe', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RecipeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('step_number', models.PositiveIntegerField(help_text='Step number in the cooking process')),
                ('instruction', models.TextField(help_text='Detailed cooking instruction for this step')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this step', null=True, upload_to='recipes/steps/')),
                ('estimated_time', models.PositiveIntegerField(blank=True, help_text='Estimated time for this step in minutes', null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Procedure',
                'verbose_name_plural': 'Recipe Procedures',
                'db_table': 'recipes_procedure',
                'ordering': ['recipe', 'step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount of ingredient needed', max_digits=10)),
                ('unit', models.CharField(help_text='Unit of measurement (cups, tbsp, etc.)', max_length=50)),
                ('preparation_note', models.CharField(blank=True, help_text='How to prepare ingredient (chopped, minced, etc.)', max_length=100)),
                ('is_optional', models.BooleanField(default=False, help_text='Whether ingredient is optional')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display ingredient in list')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'db_table': 'recipes_recipe_ingredient',
                'ordering': ['display_order'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_published', '-popularity_score'], name='recipes_rec_is_publ_90d5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category', '-created_at'], name='recipes_rec_categor_70ec1a_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author', '-created_at'], name='recipes_rec_author__0ddfe9_idx'),
        ),
    ]
