# Generated by Django 4.2.7 on 2025-09-19 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Collection name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Collection description', max_length=500)),
                ('is_public', models.BooleanField(default=True, help_text='Whether collection is visible to other users')),
                ('cover_image', models.ImageField(blank=True, help_text='Collection cover image', null=True, upload_to='collections/')),
                ('recipes_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'social_collection',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecipeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('email', 'Email'), ('link', 'Copy Link'), ('other', 'Other')], help_text='Platform where recipe was shared', max_length=20)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe Share',
                'verbose_name_plural': 'Recipe Shares',
                'db_table': 'social_recipe_share',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collection_name', models.CharField(blank=True, help_text='Optional collection name (e.g., "Weekend Cooking", "Quick Meals")', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this recipe', max_length=500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'db_table': 'social_wishlist',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[('recipe_created', 'Recipe Created'), ('recipe_viewed', 'Recipe Viewed'), ('recipe_rated', 'Recipe Rated'), ('recipe_saved', 'Recipe Saved'), ('recipe_shared', 'Recipe Shared'), ('user_followed', 'User Followed'), ('profile_updated', 'Profile Updated')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'social_user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='social_user_user_id_69e319_idx'), models.Index(fields=['activity_type', '-created_at'], name='social_user_activit_f26103_idx')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('followed', models.ForeignKey(help_text='User being followed', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(help_text='User who is following', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'db_table': 'social_follow',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField(help_text='Comment content', max_length=1000)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether comment is approved and visible')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.comment')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'social_comment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipe', '-created_at'], name='social_comm_recipe__7a4b60_idx'), models.Index(fields=['user', '-created_at'], name='social_comm_user_id_432175_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollectionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this recipe in the collection', max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_recipes', to='social.collection')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Collection Recipe',
                'verbose_name_plural': 'Collection Recipes',
                'db_table': 'social_collection_recipe',
                'ordering': ['display_order', '-created_at'],
                'unique_together': {('collection', 'recipe')},
            },
        ),
    ]
