# Generated by Django 4.2.7 on 2025-09-19 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Category name (e.g., Appetizers, Main Courses)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Category image for display', null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for category display (0 = first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this category prominently')),
                ('recipes_count', models.PositiveIntegerField(default=0, help_text='Number of recipes in this category')),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], help_text='Difficulty level name', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this difficulty level means', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for difficulty display (0 = easiest)')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji for display', max_length=50)),
            ],
            options={
                'verbose_name': 'Difficulty Level',
                'verbose_name_plural': 'Difficulty Levels',
                'db_table': 'categories_difficulty_level',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Tag name (e.g., healthy, quick, vegetarian)', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for tag display', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this tag has been used')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'categories_tag',
                'ordering': ['name'],
            },
        ),
    ]
